import {
  AirVent,
  ArrowUpDown,
  Dog,
  Cigarette,
  Sofa,
  Car,
  Briefcase,
  Music,
  Film,
  Gamepad2,
  GraduationCap,
  Shield,
  Book,
  Utensils,
  Calculator,
  LineChart,
  ShoppingCart,
  Users,
  Presentation,
  Package,
  ClipboardList,
  DollarSign,
  Database,
  Code,
  Smartphone,
  PenTool,
  Globe,
  Stethoscope,
  Thermometer,
  Activity,
  Scissors,
  Brain,
  Heart,
  Palette,
  Feather,
  Camera,
  Video,
  BookOpen,
  Building,
  Zap,
  HardHat,
  Scale,
  Gavel,
  Edit,
  MessageCircle,
  Share2,
  Coffee,
  ChefHat,
  MonitorDot,
  PartyPopper,
  Building2,
  Beaker,
  Axe,
  Flame,
  Siren,
  Plane,
  Ban,
} from "lucide-react";

export const initialPreferences = {
  roommate: {
    overview: {
      rentRange: 10000,
      bedrooms: 1,
      bathrooms: 1,
      minSize: 20,
    },
    details: {
      AC: true,
      Parking: true,
      Balcony: true,
      Furnished: true,
      Elevator: true,
      "Pet Friendly": true,
      "Smoking Allowed": true,
    },
    leaseDuration: {
      moveInDateStart: new Date().getTime(),
    },
    location: {
      address: {
        street: undefined,
        city: undefined,
        coordinates: [],
      },
      radius: 1000,
    },
  },
  apartment: {
    ageRange: [18, 60],
    gender: [],
    occupations: [],
    sharedInterests: [],
  },
};

export const iconMapRoommatePreferences = {
  AC: AirVent,
  Parking: Car,
  Balcony: ArrowUpDown,
  Furnished: Sofa,
  Elevator: ArrowUpDown,
  "Pet Friendly": Dog,
  "Smoking Allowed": Cigarette,
};

// export const occupationOptions = [
//   { value: "Soldier", label: "Soldier", icon: Shield },
//   { value: "Student", label: "Student", icon: GraduationCap },
//   { value: "Part-Time", label: "Part-Time Worker", icon: Clock },
//   { value: "Full-Time", label: "Full-Time Employee", icon: Briefcase },
//   { value: "Freelancer", label: "Freelancer", icon: Laptop },
// ];

export const occupationOptions = [
  { value: "Accountant", label: "Accountant", icon: Calculator },
  { value: "BusinessAnalyst", label: "Business Analyst", icon: Book },
  { value: "Consultant", label: "Consultant", icon: Briefcase },
  { value: "Entrepreneur", label: "Entrepreneur", icon: LineChart },
  { value: "FinancialAdvisor", label: "Financial Advisor", icon: DollarSign },
  {
    value: "HumanResourcesManager",
    label: "Human Resources Manager",
    icon: Users,
  },
  { value: "MarketingManager", label: "Marketing Manager", icon: ShoppingCart },
  { value: "ProductManager", label: "Product Manager", icon: Package },
  { value: "ProjectManager", label: "Project Manager", icon: ClipboardList },
  { value: "SalesManager", label: "Sales Manager", icon: Presentation },
  { value: "DataAnalyst", label: "Data Analyst", icon: Database },
  { value: "Programmer", label: "Programmer", icon: Code },
  { value: "SoftwareDeveloper", label: "Software Developer", icon: Smartphone },
  { value: "UXDesigner", label: "UX Designer", icon: PenTool },
  { value: "WebDeveloper", label: "Web Developer", icon: Globe },
  { value: "Dentist", label: "Dentist", icon: Book },
  { value: "Doctor", label: "Doctor", icon: Stethoscope },
  { value: "Nurse", label: "Nurse", icon: Thermometer },
  {
    value: "OccupationalTherapist",
    label: "Occupational Therapist",
    icon: Activity,
  },
  { value: "Pharmacist", label: "Pharmacist", icon: Scissors },
  { value: "PhysicalTherapist", label: "Physical Therapist", icon: Activity },
  { value: "Psychologist", label: "Psychologist", icon: Brain },
  { value: "RegisteredNurse", label: "Registered Nurse", icon: Heart },
  { value: "Veterinarian", label: "Veterinarian", icon: Dog },
  { value: "Actor", label: "Actor", icon: Film },
  { value: "Artist", label: "Artist", icon: Palette },
  { value: "Designer", label: "Designer", icon: PenTool },
  { value: "GraphicDesigner", label: "Graphic Designer", icon: Feather },
  { value: "HairStylist", label: "Hair Stylist", icon: Scissors },
  { value: "MakeupArtist", label: "Makeup Artist", icon: Feather },
  { value: "Photographer", label: "Photographer", icon: Camera },
  { value: "VideoEditor", label: "Video Editor", icon: Video },
  { value: "Librarian", label: "Librarian", icon: Book },
  { value: "SocialWorker", label: "Social Worker", icon: Users },
  { value: "Teacher", label: "Teacher", icon: GraduationCap },
  { value: "Translator", label: "Translator", icon: Globe },
  { value: "YogaInstructor", label: "Yoga Instructor", icon: Activity },
  { value: "Architect", label: "Architect", icon: Building },
  { value: "Electrician", label: "Electrician", icon: Zap },
  { value: "Engineer", label: "Engineer", icon: HardHat },
  { value: "Attorney", label: "Attorney", icon: Scale },
  { value: "Lawyer", label: "Lawyer", icon: Gavel },
  { value: "Editor", label: "Editor", icon: Edit },
  { value: "Journalist", label: "Journalist", icon: Edit },
  {
    value: "PublicRelationsSpecialist",
    label: "Public Relations Specialist",
    icon: MessageCircle,
  },
  { value: "SocialMediaManager", label: "Social Media Manager", icon: Share2 },
  { value: "Writer", label: "Writer", icon: PenTool },
  { value: "Bartender", label: "Bartender", icon: Coffee },
  { value: "Chef", label: "Chef", icon: ChefHat },
  {
    value: "CustomerServiceRepresentative",
    label: "Customer Service Representative",
    icon: MonitorDot,
  },
  { value: "EventPlanner", label: "Event Planner", icon: PartyPopper },
  { value: "RealEstateAgent", label: "Real Estate Agent", icon: Building2 },
  { value: "Mechanic", label: "Mechanic", icon: Beaker },
  { value: "Plumber", label: "Plumber", icon: Axe },
  { value: "Firefighter", label: "Firefighter", icon: Flame },
  { value: "PoliceOfficer", label: "Police Officer", icon: Siren },
  { value: "Pilot", label: "Pilot", icon: Plane },
  { value: "Student", label: "Student", icon: Book },
  { value: "Solider", label: "Solider", icon: Shield },
  { value: "Unemployed", label: "Unemployed", icon: Ban },
  { value: "Retired", label: "Retired", icon: Ban },
];

export const interestOptions = [
  { value: "Music", label: "Music", icon: Music },
  { value: "Movies", label: "Movies", icon: Film },
  { value: "Sports", label: "Sports", icon: Gamepad2 },
  { value: "Reading", label: "Reading", icon: Book },
  { value: "Cooking", label: "Cooking", icon: Utensils },
];
